import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import AppLayout from "../components/AppLayout";
import styles from "../styles/Home.module.css";
import { colors } from "./../styles/theme";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppLayout>
        <section>
          <h1>MeroMero</h1>

          <h2>
            Share your favorites comp <br /> with developers
          </h2>
        </section>
      </AppLayout>
      <style jsx>{`
        section {
          display: grid;
          height: 100%;
          place-items: center;
          place-content: center;
        }
        h1 {
          color: ${colors.primary};
          font-weight: bold;
          margin-bottom: 0;
          font-size: 24px;
        }
        h2 {
          color: ${colors.secondary};
          font-size: 16px;
          margin: 0;
        }
      `}</style>
    </>
  );
};

export default Home;
